services:
  development:
    build:
      context: .
    # tty: true
    # privileged: true
    volumes:
      - ..:/workspace
      # - type: bind
      #   source: /dev/bus/usb
      #   target: /dev/bus/usb
      #   consistency: cached
