services:
  development:
    build:
      context: .
    # privileged: true
    command: [ "/bin/bash", "-c", "trap 'exit 0' SIGTERM; while true; do sleep 1; done" ]
    volumes:
      - ..:/workspace
      # - type: bind
      #   source: /dev/bus/usb
      #   target: /dev/bus/usb
      #   consistency: cached
